### PR TITLE
Refactor the NodeNames list

### PR DESCRIPTION
**Pull request by alejandromontero**

### CODE REVIEW

**Comment by fenech** [comment]
It wasn't long ago that these lists were being generated using `seq`, which inserts a newline between each element. So what's changed? If we need to use spaces now, then I guess we should be making this same change in every config file?

...or removing the config files from the git repo!

By the way, the branch and commit title could be made more descriptive, in this case something in the commit title like "Change newlines and spaces in nodeNames list" would make it a lot easier to search for the commit that introduced that change.

**Comment by alejandromontero** [comment]
Actually we could still use seq, I used print because on of the nodes died and it seemed the best option. Both spaces or newlines work perfectly.We could change print to seq without issue. What do you think?

**Comment by fenech** [comment]
I don't think you understood my comment. I'm confused why you changed it from `\n` to ` `. If you're saying it doesn't matter either way, then this pull request doesn't do anything useful at all, so let's close it and move on.

It was me to told you to use `printf` (a standard built-in feature of bash + other shells) instead of `seq` (a non-standard external program).

**Comment by fenech** [comment]
If using a newline is now broken for some reason, then you should also check every other config in the directory at the same time and remove all usages of `printf` + `\n` or `seq` without a custom `-s`. Or find out what broke it and undo it.

**Comment by alejandromontero** [comment]
Tested it works OK with both spaces and newlines. I made the change to maintain consistency as we never use them in any other cluster description file. In any case, it is safe to put down this pull request.

**Comment by fenech** [comment]
The point is that we _do_ use a newline all over the place, because that's exactly what `seq` was doing before!

**Pull request closed without merging**
